#!/usr/bin/env bash
# ── CISEM UNIVERSAL CREATION GATE (WARN) — the mandatory-minimums check that fires on EVERY
# governed creation, closing the DECLARED≠WIRED hole (Governor audit 2026-07-20/21, RI-0009).
# Before this, tag+status was enforced ONLY on plan alignment tables ([TAG-STATUS]) and IDs only
# on CISEM-{TYPE}-{SEQ} nodes ([I9]) — so skills/agents/templates/checks/registries/ad-hoc files
# could be born UNGOVERNED (8+ found in the audit). This scans the governed tree and flags any
# file missing a `tags:` line OR a `Status:` line. WARN-only now (SWIFT-safe); the BLOCK form is
# ARCH-00407 Phase 0. Vocabulary-VALIDITY (status ∈ the right enum) is a follow-on — statuses are
# context-scoped across multiple enums (node/planning/archive/root-insights), reconciliation pending.
# Usage: bash dna/checks/creation-gate.sh   (exit 0 always — WARN; findings printed for [ZF]/RQC).
repo="$(git rev-parse --show-toplevel 2>/dev/null || echo .)"; cd "$repo" 2>/dev/null || exit 0

echo "[CREATION-GATE] every governed file must carry a tag AND a status (mandatory minimum; WARN — ARCH-00407 Phase 0 is the BLOCK):"
missing=0
# Governed dirs where every .md is a governed artifact (READMEs + templates + index/manifest stubs are exempt).
# find (not git ls-files) so NEW/untracked ungoverned files — the whole point — are caught too, and
# git pathspec **/ quirks (which miss direct children) can't create false-negatives.
# PARKED-ITEM COVERAGE (Governor decree 2026-07-21): "all parked items MUST receive tag + status." The
# parking locations — dna/ibd (IBD raw parks), dna/queue (parked/queued build-prompts), dna/audits (explicit
# PARK targets + audit reports), dna/learning-registry (parked designs/RIs) — are now ENUMERATED here too, so a
# parked item missing tag/status is flagged MECHANICALLY, not left to the model's memory. HONEST LIMIT: this is
# a presence-FLAG at commit, not an auto-INJECTOR — the model still chooses the correct tag+status (a machine
# cannot guess the right ones); the hardwire is that a miss can no longer pass silently.
# V10 FIX (creation-gate blind-spot, Governor audit 2026-07-21): the enumeration previously omitted
# repo-root and dna/-root LOOSE files (-maxdepth 1 on both), so files born directly in those two spots
# (not under any of the named governed subdirectories) escaped the gate entirely — a false clean bill.
# Universal-by-default (Principle 18B): every governed dir is enumerated, AND both root levels that can
# hold loose governed .md files. CLAUDE.md's declared exception (ARCH-00011 §2) is preserved: it is NOT
# added to the case-exemption list below because it already carries real Tags:/Status: fields and passes
# the presence check on its own merits — no special-case needed.
for f in $( { find dna/corespines dna/protocols dna/planning dna/schema dna/vocabulary .claude/agents .claude/skills \
             dna/ibd dna/queue dna/audits dna/learning-registry \
             -type f -name '*.md' 2>/dev/null; \
             find . -maxdepth 1 -type f -name '*.md' 2>/dev/null; \
             find dna -maxdepth 1 -type f -name '*.md' 2>/dev/null; } | sort -u); do
  base="$(basename "$f")"
  # Exemptions (declared, not silent): READMEs, templates (own PLACEHOLDER convention), split-index stubs.
  case "$base" in README.md|*-template.md|*-index.md|BUILD-PROMPT-template.md) continue;; esac
  case "$f" in *dna/templates/*) continue;; esac
  # Mechanical/verbatim outputs (not model-authored governed artifacts): raw-activity transcript snapshots
  # are auto-generated by save-raw-activity.sh (session-UUID-keyed) — exempt like dated audit snapshots.
  case "$f" in *dna/learning-registry/raw-activity/*) continue;; esac
  # Presence check (mandatory minimum): a governed file must declare a tags: and a Status: SOMEWHERE
  # (frontmatter `tags:`, bold `**Status:**`, mid-line `| Status:`, or a deeper governance header all count).
  # Whole-file, case-insensitive — WARN gate, so the tiny body-prose false-positive risk is acceptable.
  has_tag="$(grep -ciE 'tags:' "$f" 2>/dev/null)"
  has_status="$(grep -ciE 'status:' "$f" 2>/dev/null)"
  if [ "${has_tag:-0}" -eq 0 ] || [ "${has_status:-0}" -eq 0 ]; then
    miss=""
    [ "${has_tag:-0}" -eq 0 ] && miss="no tag"
    [ "${has_status:-0}" -eq 0 ] && miss="${miss:+$miss + }no status"
    echo "   UNGOVERNED: $f ($miss)"
    missing=$((missing+1))
  fi
done
if [ "$missing" -eq 0 ]; then
  echo "   (none — every governed file carries a tag + a status)"
else
  echo "   -> $missing governed file(s) born without tag/status. Fix at creation, not after (Principle 17 / A5 / Governor decree)."
fi
exit 0
